print("   /|")
print("  / |")
print(" /  |")
print("/___|")
print(" ")
character_name="John"
character_age="35"
print("There once was a man named John,")
print("He was 35 years old.")
print("He like the name John, but not the age 35.")
print(" ")
print("There once was a man named " + character_name + ",")
print("He was " + character_age + " years old.")
print("He like the name " + character_name + ", but not the age " + character_age +".")
print(" ")
print(" ")
print(" ")
print("Working\nwith\nStrings.")
print(" ")
print("Working \"with\" Strings.")
print(" ")
phrase="Some\ndumb\nshit"
print(phrase)
print(" ")
print(phrase+"\nis cool.")
print(" ")
print(phrase.lower())
print(" ")
print(phrase.upper())
print(" ")
print(phrase.isupper())
print(" ")
print(phrase.upper().isupper())
print("")
print(len(phrase)) # len() = length()
print("")
print(phrase[3])
print("")
print(phrase.index("e"))
print("")
print(phrase.replace("shit", "Asshole"))
